### ISSUE TITLE
BED file issue #2

### ISSUE THREAD

**Issue by SixEl27** [IARCbioinfo/mutect-nf#22]
During the BED file splitting regarding the option "-nsplit", it happen that the split create coordinate in the bed file where the start position is exactly the same as the end position, leading to an error "Problem reading the interval file caused by Badly formed genome location".

**Comment by tdelhomme** [comment]
@SixEl27 I need your bed file and the number of split you used, could send them to me by mail? thanks!

**Comment by SixEl27** [comment]
Dear Mutect-nf developer,


Please find enclosed the bed file I used.


The parameter "-nsplit" was defined at 100.


Let me know if you need any other informations.


Best,


Alexis


Alexis Robitaille, PhD Student
Infection and Cancer Biology Group
International Agency for Research on Cancer
World Health Organisation
150 Cours Albert Thomas
69372 Lyon CEDEX 08, France

Mob. +33 (0)6 76 94 25 85
E-Mail: robitaillea@students.iarc.fr




________________________________

**Comment by SixEl27** [comment]
[mm10_exome_Agilent_sort.bed.tar.gz](https://github.com/IARCbioinfo/mutect-nf/files/1024745/mm10_exome_Agilent_sort.bed.tar.gz)
